version: "2"

services:
  sut:
    build: .
    privileged: true
    volumes:
      - cache:/cache
      - snapshots:/snapshots
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      BACKUP_CRON: ""
      RESTIC_PASSWORD: topsecret
      LOG_LEVEL: debug
      TAGS: foo=bar
      HOST: foobar
    depends_on:
      - test-service-1
      - test-service-2

  test-service-1:
    image: alpine
    volumes:
      - test-data-1:/data
    command: tail -f /dev/null

  test-service-2:
    image: alpine
    volumes:
      - test-data-1:/data-1
      - test-data-2:/data-2
    command: tail -f /dev/null

volumes:
  cache:
  snapshots:
  test-data-1:
  test-data-2:
