version: "2"

services:
  volume-keeper:
    build: .
    labels:
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-socket: 1
    volumes:
      - cache:/cache
      - snapshots:/snapshots
    tmpfs:
      - /tmp

volumes:
  cache:
  snapshots:
