version: "2"

services:
  restic:
    build: .
    privileged: true
    labels:
      io.balena.features.supervisor-api: 1
    volumes:
      - cache:/cache
      - snapshots:/snapshots
    tmpfs:
      - /tmp

volumes:
  cache:
  snapshots:
  test-volume-1:
  test-volume-2:
